/**
 * Narrative Guide Generator v2.2
 * 
 * PHILOSOPHY: Voice immersion over statistical compliance
 * PRINCIPLE: Every example comes from the corpus or is omitted
 * NEW IN v2.2: Micro-rhythm annotations on examples
 * 
 * Structure:
 * - Voice in One Page (synthesis)
 * - Voice Immersion (extended examples with human-feel annotations)
 * - Anti-Patterns to Avoid (narrative, not tables)
 * - Punctuation & Mechanical Tells
 * - Validation Metrics (check after writing)
 */

import fs from 'fs/promises';
import path from 'path';
import { detectMicroRhythms, annotateExample, annotateSequence } from '../utils/micro-rhythm.js';
import type { VocabularyAnalysis } from '../analyzers/vocabulary.js';
import type { SentenceAnalysis } from '../analyzers/sentence.js';
import type { VoiceMarkers } from '../analyzers/voice-markers.js';
import type { ParagraphAnalysis } from '../analyzers/paragraph.js';
import type { PunctuationAnalysis } from '../analyzers/punctuation.js';
import type { FunctionWordAnalysis } from '../analyzers/function-words.js';
import type { ArgumentFlowAnalysis } from '../analyzers/argument-flow.js';
import type { ParagraphTransitionsAnalysis } from '../analyzers/paragraph-transitions.js';

export interface NarrativeGuideParams {
  corpus_name: string;
  corpus_dir: string;
}

export interface NarrativeGuideResult {
  success: boolean;
  guide_path: string;
}

async function generateNarrativeGuideInternal(params: NarrativeGuideParams): Promise<NarrativeGuideResult> {
  const { corpus_name, corpus_dir } = params;
  
  const corpusPath = path.join(corpus_dir, corpus_name);
  const analysisDir = path.join(corpusPath, 'analysis');
  const articlesDir = path.join(corpusPath, 'articles');
  
  await fs.mkdir(corpusPath, { recursive: true });
  
  const vocab = await loadJSON<VocabularyAnalysis>(analysisDir, 'vocabulary.json');
  const sentence = await loadJSON<SentenceAnalysis>(analysisDir, 'sentence.json');
  const voice = await loadJSON<VoiceMarkers>(analysisDir, 'voice.json');
  const paragraph = await loadJSON<ParagraphAnalysis>(analysisDir, 'paragraph.json', true);
  const punctuation = await loadJSON<PunctuationAnalysis>(analysisDir, 'punctuation.json', true);
  const functionWords = await loadJSON<FunctionWordAnalysis>(analysisDir, 'function-words.json', true);
  
  // Load pre-computed analysis from JSON (generated by analyze_corpus)
  const argumentFlow = await loadJSON<ArgumentFlowAnalysis>(analysisDir, 'argument-flow.json', true);
  const paragraphTransitions = await loadJSON<ParagraphTransitionsAnalysis>(analysisDir, 'paragraph-transitions.json', true);
  
  if (!vocab || !sentence || !voice) {
    throw new Error('Missing required analysis files (vocabulary, sentence, voice)');
  }
  
  if (!argumentFlow || !paragraphTransitions) {
    throw new Error('Missing argument-flow.json or paragraph-transitions.json - run analyze_corpus first');
  }
  
  // Increased from 30 to 60 examples for richer immersion
  const examples = await extractExampleParagraphs(articlesDir, 60);
  const sequences = await extractMultiParagraphSequences(articlesDir);
  
  const metadata = JSON.parse(
    await fs.readFile(path.join(corpusPath, 'corpus.json'), 'utf-8')
  );
  
  const guide = generateNarrativeContent(
    corpus_name,
    metadata,
    vocab,
    sentence,
    voice,
    paragraph,
    punctuation,
    functionWords,
    argumentFlow,
    paragraphTransitions,
    examples,
    sequences
  );
  
  const guidePath = path.join(corpusPath, `writing_style_${corpus_name}_narrative.md`);
  await fs.writeFile(guidePath, guide, 'utf-8');
  
  return {
    success: true,
    guide_path: guidePath
  };
}

async function loadJSON<T>(dir: string, filename: string, optional: boolean = false): Promise<T | null> {
  try {
    const content = await fs.readFile(path.join(dir, filename), 'utf-8');
    return JSON.parse(content) as T;
  } catch (e) {
    if (optional) return null;
    throw e;
  }
}

async function extractExampleParagraphs(articlesDir: string, count: number): Promise<{
  openings: string[];
  middles: string[];
  closings: string[];
  technical: string[];
  personal: string[];
  transitions: string[];
  counterpoints: string[];
  admissions: string[];
}> {
  const files = await fs.readdir(articlesDir);
  const markdownFiles = files.filter(f => f.endsWith('.md'));
  
  const openings: string[] = [];
  const middles: string[] = [];
  const closings: string[] = [];
  const technical: string[] = [];
  const personal: string[] = [];
  const transitions: string[] = [];
  const counterpoints: string[] = [];
  const admissions: string[] = [];
  
  const cleanParagraph = (text: string): string => {
    return text
      .replace(/\[([^\]]*)\]\([^\)]*\)/g, '$1')
      .replace(/^#{1,6}\s+/gm, '')
      .replace(/\*\*([^\*]+)\*\*/g, '$1')
      .replace(/\*([^\*]+)\*/g, '$1')
      .replace(/`([^`]+)`/g, '$1')
      .replace(/\[\]\(\)/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  };
  
  for (const file of markdownFiles) {
    const content = await fs.readFile(path.join(articlesDir, file), 'utf-8');
    const withoutFrontmatter = content.replace(/^---[\s\S]*?---\n\n/, '');
    const paras = withoutFrontmatter.split(/\n\n+/).filter(p => {
      const words = p.split(/\s+/).length;
      const hasNoHeaderMarker = !p.trim().startsWith('#');
      const hasSubstantialText = p.trim().length > 100;
      return words >= 30 && words <= 300 && hasNoHeaderMarker && hasSubstantialText;
    });
    
    if (paras.length === 0) continue;
    
    // Increased from count/5 to count/8 to allow more examples per category
    const perCategory = Math.ceil(count / 8);
    
    if (openings.length < perCategory && paras[0]) {
      openings.push(cleanParagraph(paras[0]));
    }
    
    const middleStart = Math.floor(paras.length * 0.3);
    const middleEnd = Math.floor(paras.length * 0.7);
    const middlePara = paras.slice(middleStart, middleEnd)[0];
    if (middles.length < perCategory && middlePara) {
      middles.push(cleanParagraph(middlePara));
    }
    
    if (closings.length < perCategory && paras[paras.length - 1]) {
      closings.push(cleanParagraph(paras[paras.length - 1]));
    }
    
    for (const para of paras.slice(1, -1)) {
      const lower = para.toLowerCase();
      const isTechnical = /\d+\s*(nm|kg|mm|watts|hz|fps|%|px|kb|mb|gb)/i.test(para) || 
                         ['specifications', 'performance', 'features', 'metrics', 'data'].some(w => lower.includes(w));
      const isPersonal = ["i've", "my", "in my experience", "i found", "i tested"].some(w => lower.includes(w));
      const isTransition = ['however', 'but then', 'that said', 'on the other hand', 'moving on', 'now let'].some(w => lower.includes(w));
      const isCounterpoint = ['but', 'however', 'although', 'despite', 'yet', 'still'].some(w => lower.startsWith(w) || lower.includes('. but ') || lower.includes('. however '));
      const isAdmission = ["i don't", "i'm not sure", "i was wrong", "i failed", "i struggled", "mistake", "honestly", "to be fair"].some(w => lower.includes(w));
      
      if (isTechnical && technical.length < perCategory) {
        technical.push(cleanParagraph(para));
      } else if (isPersonal && personal.length < perCategory) {
        personal.push(cleanParagraph(para));
      } else if (isTransition && transitions.length < perCategory) {
        transitions.push(cleanParagraph(para));
      } else if (isCounterpoint && counterpoints.length < perCategory) {
        counterpoints.push(cleanParagraph(para));
      } else if (isAdmission && admissions.length < perCategory) {
        admissions.push(cleanParagraph(para));
      }
    }
  }
  
  return { openings, middles, closings, technical, personal, transitions, counterpoints, admissions };
}

async function extractMultiParagraphSequences(articlesDir: string): Promise<string[]> {
  const files = await fs.readdir(articlesDir);
  const markdownFiles = files.filter(f => f.endsWith('.md'));
  
  const sequences: string[] = [];
  
  for (const file of markdownFiles) {
    // Increased from 3 to 8 sequences - this is the most valuable immersion content
    if (sequences.length >= 8) break;
    
    const content = await fs.readFile(path.join(articlesDir, file), 'utf-8');
    const withoutFrontmatter = content.replace(/^---[\s\S]*?---\n\n/, '');
    const paras = withoutFrontmatter.split(/\n\n+/).filter(p => {
      const words = p.split(/\s+/).length;
      return words >= 30 && words <= 300 && !p.trim().startsWith('#');
    });
    
    if (paras.length >= 5) {
      const startIdx = Math.floor(paras.length * 0.3);
      const sequence = paras.slice(startIdx, startIdx + 3).join('\n\n');
      if (sequence.split(/\s+/).length >= 150) {
        sequences.push(sequence);
      }
    }
  }
  
  return sequences;
}

function formatWriterName(name: string): string {
  return name.split(/[-_]/).map(w => 
    w.charAt(0).toUpperCase() + w.slice(1)
  ).join(' ');
}


function generateNarrativeContent(
  writerName: string,
  metadata: any,
  vocab: VocabularyAnalysis,
  sentence: SentenceAnalysis,
  voice: VoiceMarkers,
  paragraph: ParagraphAnalysis | null,
  punctuation: PunctuationAnalysis | null,
  functionWords: FunctionWordAnalysis | null,
  argumentFlow: ArgumentFlowAnalysis,
  paragraphTransitions: ParagraphTransitionsAnalysis,
  examples: any,
  sequences: string[]
): string {
  const lines: string[] = [];
  
  // Header
  lines.push(`# ${formatWriterName(writerName)} Writing Voice (Narrative Guide)`);
  lines.push('');
  lines.push("**Philosophy:** This guide teaches you to channel this writer's voice through immersion, not rule-following.");
  lines.push('');
  lines.push('**How to use:** Read the examples aloud. Feel the rhythm. Let the voice settle into your mind. THEN write. The statistics at the end are just validation checkpoints.');
  lines.push('');
  lines.push('---');
  lines.push('');
  
  // ============================================================
  // THE VOICE IN ONE PAGE
  // ============================================================
  lines.push('## THE VOICE IN ONE PAGE');
  lines.push('');
  lines.push('*If you only read one section, read this.*');
  lines.push('');
  
  // WHO
  lines.push('### WHO IS THIS WRITER?');
  lines.push('');
  
  const hasPersonal = voice.firstPerson.frequency > 0.3;
  const hasConfidence = voice.hedgingLanguage.frequency < 0.5;
  const hasBritish = vocab.britishMarkers.length > 0;
  
  if (hasPersonal && hasConfidence) {
    lines.push('> **An experienced practitioner who shares hard-won knowledge with confident directness.**');
  } else if (hasPersonal) {
    lines.push('> **A thoughtful expert who balances personal experience with measured caution.**');
  } else if (hasConfidence) {
    lines.push('> **An authoritative voice that explains complex topics with clarity and confidence.**');
  } else {
    lines.push('> **A knowledgeable guide who explains topics with measured authority.**');
  }
  lines.push('');
  
  lines.push('Not a guru. Not a marketing department. A real person with:');
  lines.push('');
  
  const identity: string[] = [];
  if (hasPersonal) identity.push('- **Personal testing experience** - speaks from actual use, not theory');
  if (hasConfidence) identity.push('- **Direct communication style** - minimal hedging, confident statements');
  if (hasBritish) identity.push('- **British English** throughout (whilst, colour, optimise)');
  if (voice.conversationalMarkers.length > 3) {
    identity.push('- **Conversational markers** - "look", "well", "actually" appear naturally');
  }
  
  // DYNAMIC: Equipment specificity from corpus
  if (voice.equipmentSpecificity && voice.equipmentSpecificity.specific.length > 0) {
    const topExample = voice.equipmentSpecificity.specific[0].phrase;
    identity.push(`- **Specific product references** - "${topExample}" not generic descriptions`);
  }
  
  for (const trait of identity) lines.push(trait);
  lines.push('');
  
  // HOW THEY OPEN
  lines.push('### HOW THEY OPEN');
  lines.push('');
  
  if (argumentFlow.openingMoves.length > 0) {
    for (const move of argumentFlow.openingMoves.slice(0, 2)) {
      lines.push(`**${move.type}:** ${move.description}`);
      lines.push('');
      if (move.examples[0]) {
        lines.push('```');
        lines.push(move.examples[0]);
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('*No distinct opening patterns detected - this writer varies their approach.*');
    lines.push('');
  }
  
  // HOW THEY BUILD
  lines.push('### HOW THEY BUILD ARGUMENTS');
  lines.push('');
  
  if (argumentFlow.patterns.length > 0) {
    for (const pattern of argumentFlow.patterns.slice(0, 2)) {
      lines.push(`**${pattern.pattern}**`);
      lines.push('');
      lines.push(pattern.description);
      lines.push('');
      if (pattern.examples[0]) {
        lines.push('Example:');
        lines.push('```');
        lines.push(pattern.examples[0].fullText);
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('*Argument patterns vary - see extended examples below for organic flow.*');
    lines.push('');
  }
  
  // HOW THEY TRANSITION
  lines.push('### HOW THEY TRANSITION BETWEEN IDEAS');
  lines.push('');
  
  if (paragraphTransitions.transitions.length > 0) {
    const topTransitions = paragraphTransitions.transitions.slice(0, 3);
    for (const trans of topTransitions) {
      const linkingInfo = trans.linkingPhrase ? `"${trans.linkingPhrase}"` : trans.linkingDevice;
      lines.push(`**${trans.fromType} -> ${trans.toType}** (${linkingInfo})`);
      lines.push('');
    }
  } else {
    lines.push('*Transitions are primarily implicit - paragraphs flow naturally without explicit connectives*');
    lines.push('');
  }
  
  // CONVERSATIONAL DEVICES - DYNAMIC FROM CORPUS
  if (argumentFlow.conversationalDevices.length > 0) {
    lines.push('### KEY CONVERSATIONAL DEVICES');
    lines.push('');
    lines.push('*These micro-patterns make writing feel spoken rather than written:*');
    lines.push('');
    
    for (const device of argumentFlow.conversationalDevices.slice(0, 5)) {
      lines.push(`#### "${device.trigger}"`);
      lines.push('');
      lines.push(`**Purpose:** ${device.purpose}`);
      lines.push('');
      
      if (device.examples.length > 0) {
        lines.push('**Contexts where it appears (from this corpus):**');
        lines.push('');
        
        for (let i = 0; i < Math.min(3, device.examples.length); i++) {
          lines.push(`${i + 1}. "${device.examples[i]}"`);
          lines.push('');
        }
        
        lines.push('**When NOT to use:**');
        lines.push(`- Don't overuse (${device.trigger} appears naturally, not every paragraph)`);
        lines.push('- Avoid in formal technical specs or legal disclaimers');
        lines.push('- Skip if the sentence already has strong conversational energy');
        lines.push('');
      }
    }
  }
  
  // WHAT TO AVOID - Universal AI cliches (these are domain-agnostic)
  lines.push('### WHAT TO AVOID');
  lines.push('');
  lines.push('**Universal AI cliches to eliminate:**');
  lines.push('');
  lines.push('1. **AI tells** - "delve", "leverage", "unlock", "seamless", "robust"');
  lines.push('2. **Marketing speak** - "game-changer", "revolutionary", "cutting-edge"');
  lines.push('3. **Generic references** - use specific names from your domain');
  lines.push('4. **Uniform rhythm** - every sentence the same length (15-20 words)');
  lines.push('5. **Perfect narratives** - admitting mistakes/complexity is authenticity');
  lines.push('');
  
  // QUICK VALIDATION
  lines.push('### QUICK VALIDATION CHECKPOINT');
  lines.push('');
  lines.push('After writing, check:');
  lines.push('');
  lines.push("- [ ] Sentence lengths vary wildly (some 5-8 words, some 25-40 words)");
  lines.push("- [ ] First-person appears but isn't clustered at sentence starts");
  if (voice.conversationalMarkers.length > 0) {
    const markers = voice.conversationalMarkers.slice(0, 3).map(m => `"${m.word}"`).join(', ');
    lines.push(`- [ ] Conversational markers (${markers}) present`);
  }
  lines.push(`- [ ] ${hasBritish ? 'British spelling throughout' : 'Consistent spelling'}`);
  if (voice.equipmentSpecificity && voice.equipmentSpecificity.specific.length > 0) {
    lines.push('- [ ] Specific product/equipment names (not generic)');
  }
  lines.push('');
  
  lines.push('---');
  lines.push('');
  
  // ============================================================
  // VOICE IMMERSION - EXTENDED EXAMPLES
  // ============================================================
  lines.push('## VOICE IMMERSION: EXTENDED EXAMPLES');
  lines.push('');
  lines.push('*Read these aloud. Let the rhythm and energy settle into your mind.*');
  lines.push('');
  
  // Opening Examples - ALL FROM CORPUS
  if (examples.openings.length > 0) {
    lines.push('### Opening Moves - How This Writer Starts');
    lines.push('');
    lines.push('*Categorized by approach - notice which patterns this writer favors:*');
    lines.push('');
    
    const categorized = {
      directAction: [] as string[],
      personalStory: [] as string[],
      problemStatement: [] as string[],
      observation: [] as string[],
      protectiveWarning: [] as string[]
    };
    
    for (const opening of examples.openings) {
      const lower = opening.toLowerCase();
      const firstSentence = opening.split(/[.!?]/)[0].toLowerCase();
      
      if (firstSentence.match(/^(right|okay|so|look)/)) {
        categorized.directAction.push(opening);
      } else if (lower.includes('before') || lower.includes('caveat') || lower.includes('warning')) {
        categorized.protectiveWarning.push(opening);
      } else if (lower.includes("i've") || lower.includes('i discovered') || lower.includes('i fell')) {
        categorized.personalStory.push(opening);
      } else if (lower.includes('problem') || lower.includes('issue') || lower.includes('challenge')) {
        categorized.problemStatement.push(opening);
      } else {
        categorized.observation.push(opening);
      }
    }
    
    // Show each category with corpus examples - increased from 2 to 3 per category
    if (categorized.directAction.length > 0) {
      lines.push('#### Direct Action Openings');
      lines.push("*Starts with immediate momentum - \"we're already moving\"*");
      lines.push('');
      for (const ex of categorized.directAction.slice(0, 3)) {
        lines.push('```');
        lines.push(ex);
        lines.push('```');
        lines.push('');
      }
    }
    
    if (categorized.protectiveWarning.length > 0) {
      lines.push('#### Protective Warning Openings');
      lines.push('*Builds trust by acknowledging risks before pitching solutions*');
      lines.push('');
      for (const ex of categorized.protectiveWarning.slice(0, 3)) {
        lines.push('```');
        lines.push(ex);
        lines.push('```');
        lines.push('');
      }
    }
    
    if (categorized.personalStory.length > 0) {
      lines.push('#### Personal Story Openings');
      lines.push('*Establishes authority through personal discovery/experience*');
      lines.push('');
      for (const ex of categorized.personalStory.slice(0, 3)) {
        lines.push('```');
        lines.push(ex);
        lines.push('```');
        lines.push('');
      }
    }
    
    if (categorized.problemStatement.length > 0) {
      lines.push('#### Problem Statement Openings');
      lines.push('*Identifies the pain point before offering solution*');
      lines.push('');
      for (const ex of categorized.problemStatement.slice(0, 3)) {
        lines.push('```');
        lines.push(ex);
        lines.push('```');
        lines.push('');
      }
    }
    
    if (categorized.observation.length > 0) {
      lines.push('#### Observation Openings');
      lines.push('*Starts with a clear statement of fact or context*');
      lines.push('');
      for (const ex of categorized.observation.slice(0, 3)) {
        lines.push('```');
        lines.push(ex);
        lines.push('```');
        lines.push('');
      }
    }
    
    // Pattern summary
    lines.push('**Opening Pattern Summary:**');
    lines.push('');
    const counts = Object.entries(categorized).filter(([_, v]) => v.length > 0);
    counts.sort((a, b) => b[1].length - a[1].length);
    const totalOpenings = examples.openings.length;
    for (const [type, exampleArray] of counts) {
      const label = type.replace(/([A-Z])/g, ' $1').trim();
      lines.push(`- ${label}: ${exampleArray.length} examples (${((exampleArray.length / totalOpenings) * 100).toFixed(0)}%)`);
    }
    if (counts.length > 0) {
      lines.push('');
      lines.push(`**Dominant approach:** ${counts[0][0].replace(/([A-Z])/g, ' $1').trim()}`);
    }
    lines.push('');
  }
  
  // Personal Experience Examples - FROM CORPUS ONLY with micro-rhythm annotations
  if (examples.personal.length > 0) {
    lines.push('### Personal Experience - Authority from Testing');
    lines.push('');
    lines.push('When this writer shares personal experience, notice not just *what* they say but *how* they say it:');
    lines.push('');
    
    for (let i = 0; i < Math.min(3, examples.personal.length); i++) {
      lines.push(`**Example ${i + 1}:**`);
      lines.push('');
      lines.push(annotateExample(examples.personal[i], 3));
    }
  }
  
  // Technical Examples - FROM CORPUS ONLY with annotations
  if (examples.technical.length > 0) {
    lines.push('### Technical Detail - Grounded in Specifics');
    lines.push('');
    lines.push('Technical paragraphs blend specifications with practical implications. Notice how the human feel persists even in technical content:');
    lines.push('');
    
    for (let i = 0; i < Math.min(3, examples.technical.length); i++) {
      lines.push(`**Example ${i + 1}:**`);
      lines.push('');
      lines.push(annotateExample(examples.technical[i], 2));
    }
  }

  // Transition Examples - FROM CORPUS ONLY with annotations
  if (examples.transitions.length > 0) {
    lines.push('### Transitions - How Ideas Connect');
    lines.push('');
    lines.push('*Notice how this writer moves between thoughts - not with formal connectives but with natural pivots:*');
    lines.push('');
    
    for (let i = 0; i < Math.min(3, examples.transitions.length); i++) {
      lines.push(`**Example ${i + 1}:**`);
      lines.push('');
      lines.push(annotateExample(examples.transitions[i], 2));
    }
  }

  // Counterpoint Examples - FROM CORPUS ONLY with annotations
  if (examples.counterpoints.length > 0) {
    lines.push('### Counterpoints - How Nuance Appears');
    lines.push('');
    lines.push('*Real expertise includes qualification. Notice how "but" and "however" create authentic complexity:*');
    lines.push('');
    
    for (let i = 0; i < Math.min(3, examples.counterpoints.length); i++) {
      lines.push(`**Example ${i + 1}:**`);
      lines.push('');
      lines.push(annotateExample(examples.counterpoints[i], 2));
    }
  }

  // Admission Examples - FROM CORPUS ONLY with annotations
  if (examples.admissions.length > 0) {
    lines.push('### Admissions - Vulnerability as Authenticity');
    lines.push('');
    lines.push('*These moments of honesty build trust. AI never admits uncertainty or mistakes:*');
    lines.push('');
    
    for (let i = 0; i < Math.min(3, examples.admissions.length); i++) {
      lines.push(`**Example ${i + 1}:**`);
      lines.push('');
      lines.push(annotateExample(examples.admissions[i], 2));
    }
  }

  // Multi-Paragraph Sequences - FROM CORPUS ONLY with comprehensive micro-rhythm annotations
  if (sequences.length > 0) {
    lines.push('### Voice Flow: Multi-Paragraph Sequences');
    lines.push('');
    lines.push('*This is where you really feel the voice. These extended passages show how the micro-rhythms combine to create the overall "feel". Read them aloud.*');
    lines.push('');
    
    // Show 4 sequences with full annotations (was 6 but annotations make them richer)
    for (let i = 0; i < Math.min(4, sequences.length); i++) {
      lines.push(`**Sequence ${i + 1}:**`);
      lines.push('');
      lines.push(annotateSequence(sequences[i]));
    }
    
    lines.push('**Why these sequences matter:** This is how the voice actually flows. The micro-rhythms you see annotated above - the mid-thought pivots, the casual connectors, the embedded uncertainty - these are what make writing feel like a person thinking on the page rather than AI generating text.');
    lines.push('');
  }
  
  // ============================================================
  // ARGUMENT PATTERNS IN DEPTH
  // ============================================================
  lines.push('---');
  lines.push('');
  lines.push('## HOW ARGUMENTS ARE BUILT');
  lines.push('');
  lines.push('*These are the thought patterns this writer returns to repeatedly.*');
  lines.push('');
  
  if (argumentFlow.patterns.length > 0) {
    for (const pattern of argumentFlow.patterns) {
      lines.push(`### Pattern: ${pattern.pattern}`);
      lines.push('');
      lines.push(pattern.description);
      lines.push('');
      lines.push(`**Frequency:** Used ${pattern.frequency} times in corpus`);
      lines.push('');
      
      if (pattern.examples.length > 0) {
        lines.push('**Full Example:**');
        lines.push('');
        lines.push('```');
        lines.push(pattern.examples[0].fullText);
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('*No recurring argument patterns detected - this writer varies their structure organically.*');
    lines.push('');
  }
  
  // ============================================================
  // PARAGRAPH TRANSITIONS
  // ============================================================
  lines.push('---');
  lines.push('');
  lines.push('## HOW IDEAS CONNECT: TRANSITION ANALYSIS');
  lines.push('');
  lines.push('*How this writer moves between paragraphs - the bridges, the gear shifts, the natural flow.*');
  lines.push('');
  
  if (paragraphTransitions.transitions.length > 0) {
    lines.push('### Most Common Transition Types');
    lines.push('');
    
    const topTransitions = paragraphTransitions.transitions.slice(0, 5);
    for (const trans of topTransitions) {
      const linkingInfo = trans.linkingPhrase ? `"${trans.linkingPhrase}"` : trans.linkingDevice;
      lines.push(`#### ${trans.fromType} -> ${trans.toType}`);
      lines.push('');
      lines.push(`**Linking device:** ${trans.linkingDevice === 'implicit' ? 'Implicit (no explicit connector)' : linkingInfo}`);
      lines.push(`**Frequency:** ${trans.frequency} times`);
      lines.push('');
      
      if (trans.examples.length > 0) {
        const example = trans.examples[0];
        lines.push('**How it works:**');
        lines.push('');
        lines.push('Paragraph 1 ending:');
        lines.push('```');
        const para1Sentences = example.paragraph1.split(/[.!?]+/).filter((s: string) => s.trim().length > 10);
        const lastSentences = para1Sentences.slice(-2).join('. ') + '.';
        lines.push(lastSentences);
        lines.push('```');
        lines.push('');
        
        if (trans.linkingDevice !== 'implicit') {
          lines.push('**-> Transition phrase:**');
          lines.push(`"${example.transitionSentence}"`);
          lines.push('');
        }
        
        lines.push('Paragraph 2 beginning:');
        lines.push('```');
        const para2Sentences = example.paragraph2.split(/[.!?]+/).filter((s: string) => s.trim().length > 10);
        const firstSentences = para2Sentences.slice(0, 2).join('. ') + '.';
        lines.push(firstSentences);
        lines.push('```');
        lines.push('');
        
        lines.push('**Why this works:**');
        if (trans.linkingDevice === 'implicit') {
          lines.push('- No explicit connector needed - ideas flow naturally from shared context');
          lines.push('- Reader makes the connection themselves (more engaging)');
        } else if (trans.linkingDevice === 'conversational_restart') {
          lines.push('- Conversational marker creates natural pause and redirect');
          lines.push('- Feels like spoken language, not formal writing');
        } else if (trans.linkingDevice === 'contrast') {
          lines.push('- Explicit contrast signals change in direction');
          lines.push('- Prepares reader for counter-argument or qualification');
        } else if (trans.linkingDevice === 'causal') {
          lines.push('- Clear cause-effect relationship');
          lines.push('- Logical progression from setup to conclusion');
        }
        lines.push('');
      }
    }
  }
  
  // Topic shift patterns - FROM CORPUS
  if (paragraphTransitions.topicShiftPatterns.length > 0) {
    lines.push('### Topic Shift Patterns');
    lines.push('');
    lines.push('*When this writer changes topics mid-article:*');
    lines.push('');
    
    for (const shift of paragraphTransitions.topicShiftPatterns) {
      lines.push(`**${shift.pattern}**`);
      lines.push(`- ${shift.description}`);
      lines.push(`- Used ${shift.frequency} times`);
      if (shift.examples[0]) {
        lines.push('');
        lines.push('Example transition:');
        lines.push('```');
        lines.push(shift.examples[0]);
        lines.push('```');
      }
      lines.push('');
    }
  }
  
  // Energy shifts - FROM CORPUS
  if (paragraphTransitions.energyShifts.length > 0) {
    lines.push('### Energy Shifts: How Tone Changes');
    lines.push('');
    lines.push("*The writer doesn't maintain one tone throughout. Energy shifts create rhythm and keep readers engaged.*");
    lines.push('');
    
    for (const shift of paragraphTransitions.energyShifts) {
      lines.push(`#### ${shift.from} -> ${shift.to}`);
      lines.push('');
      lines.push(shift.description);
      lines.push('');
      lines.push(`**Markers:** ${shift.markers.join(', ')}`);
      lines.push('');
      
      if (shift.examples.length > 0) {
        lines.push('**Example:**');
        lines.push('```');
        lines.push(shift.examples[0]);
        lines.push('```');
        lines.push('');
      }
    }
  }

  // ============================================================
  // ANTI-PATTERNS - DYNAMIC FROM CORPUS
  // ============================================================
  lines.push('---');
  lines.push('');
  lines.push('## ANTI-PATTERNS: WHAT BREAKS THE VOICE');
  lines.push('');
  
  lines.push('### The Mechanical Voice Problem');
  lines.push('');
  lines.push('AI-assisted writing falls into predictable traps. This writer avoids them by:');
  lines.push('');
  
  lines.push('**1. Sentence Length Variation is EXTREME**');
  lines.push('');
  lines.push('Not just "varied" - genuinely extreme. Some sentences are punchy fragments. Others expand into complex explanations that weave multiple ideas together with clauses and careful transitions.');
  lines.push('');
  lines.push(`Target distribution: ${sentence.length.mean.toFixed(1)} +/-${sentence.length.stdDev.toFixed(1)} words (high variance is good)`);
  lines.push('');
  
  // EQUIPMENT SPECIFICITY - CONDITIONAL AND DYNAMIC
  if (voice.equipmentSpecificity && 
      (voice.equipmentSpecificity.specific.length > 0 || voice.equipmentSpecificity.generic.length > 0)) {
    
    lines.push('**2. Specificity Over Generic References**');
    lines.push('');
    lines.push('This is a major authenticity marker. Generic references signal AI or marketing copy.');
    lines.push('');
    
    if (voice.equipmentSpecificity.specific.length > 0) {
      lines.push('**From this corpus - specific references used:**');
      lines.push('');
      for (const eq of voice.equipmentSpecificity.specific.slice(0, 8)) {
        lines.push(`- "${eq.phrase}"`);
      }
      lines.push('');
    }
    
    if (voice.equipmentSpecificity.generic.length > 0) {
      lines.push('**Generic patterns found (avoid these):**');
      lines.push('');
      for (const eq of voice.equipmentSpecificity.generic.slice(0, 8)) {
        lines.push(`- "${eq.phrase}" - make it specific!`);
      }
      lines.push('');
    }
    
    lines.push('**The pattern:**');
    lines.push('');
    lines.push('When you reference products, tools, or equipment:');
    lines.push('- Use the specific name, not the category');
    lines.push('- Add possessives where appropriate ("my X" proves ownership)');
    lines.push('- Include version numbers, models, or editions when relevant');
    lines.push('');
    lines.push('**Why this matters:** Specific names with possessives prove testing experience. Generic references could be written by anyone who read a press release.');
    lines.push('');
  }
  
  lines.push('**3. Perfect Narratives Signal Inauthenticity**');
  lines.push('');
  
  // Dynamic based on what the corpus actually shows
  const hasTransparency = voice.identityMarkers && voice.identityMarkers.transparencyCommitment.length > 0;
  const hasHumbleHelper = voice.identityMarkers && voice.identityMarkers.humbleHelper.length > 0;
  
  if (hasTransparency || hasHumbleHelper) {
    lines.push('This writer admits:');
    lines.push('- Mistakes made during testing');
    lines.push('- Limitations of approaches discussed');
    lines.push("- Uncertainties and \"I'm not sure\" moments");
    lines.push('');
  } else {
    lines.push('Authentic voices include:');
    lines.push('- Acknowledgment of limitations');
    lines.push('- Nuanced positions rather than absolute claims');
    lines.push('- Appropriate uncertainty markers');
    lines.push('');
  }
  lines.push("Vulnerability builds trust. Perfect stories don't.");
  lines.push('');
  
  // FORBIDDEN PHRASES - Universal AI cliches (domain-agnostic)
  lines.push('### The Forbidden Phrases (And Why)');
  lines.push('');
  lines.push('These phrases immediately break authenticity:');
  lines.push('');
  
  const forbiddenPhrases = [
    { phrase: 'delve into', why: 'No one talks like this. Use "explore", "look at", "examine"' },
    { phrase: 'leverage', why: 'Corporate speak. Use "use" or "apply"' },
    { phrase: 'unlock', why: 'Marketing hype. Use "enable", "access", "discover"' },
    { phrase: 'seamless', why: 'Empty adjective. Be specific about what works well' },
    { phrase: 'game-changer', why: 'Meaningless hype. Explain the actual impact' },
    { phrase: 'cutting-edge', why: 'Say "modern", "latest", or name the actual technology' }
  ];
  
  for (const item of forbiddenPhrases) {
    lines.push(`**"${item.phrase}"**`);
    lines.push(`  ${item.why}`);
    lines.push('');
  }
  
  // AI cliches found in THIS corpus
  if (voice.aiCliches.length > 0) {
    lines.push('**DETECTED IN CORPUS - ELIMINATE THESE:**');
    lines.push('');
    for (const cliche of voice.aiCliches.slice(0, 5)) {
      lines.push(`- "${cliche.phrase}" (${cliche.count} uses) - Must remove`);
    }
    lines.push('');
  }

  // NEW v2.1 - Hollow Intensifiers (performative authenticity)
  lines.push('### Hollow Intensifiers (The Sincerity Trap)');
  lines.push('');
  lines.push('These words signal "I\'m being authentic" which paradoxically makes writing feel LESS authentic. AI overuses them because it\'s trying to sound genuine:');
  lines.push('');
  
  const hollowIntensifiersList = [
    { phrase: 'honestly', fix: 'Just state the fact directly' },
    { phrase: 'genuinely', fix: 'Remove - if it\'s genuine, it shows' },
    { phrase: 'the real [X]', fix: 'Drop "real" - "the issue" not "the real issue"' },
    { phrase: 'really', fix: 'Often removable - "I enjoyed" not "I really enjoyed"' },
    { phrase: 'truly', fix: 'Remove - sounds like marketing copy' },
    { phrase: 'to be honest', fix: 'Implies you\'re not honest elsewhere' },
    { phrase: 'I have to say', fix: 'Just say it' },
  ];
  
  for (const item of hollowIntensifiersList) {
    lines.push(`**"${item.phrase}"** - ${item.fix}`);
    lines.push('');
  }
  
  // Show what was found in corpus
  if (voice.hollowIntensifiers && voice.hollowIntensifiers.length > 0) {
    lines.push('**Found in this corpus (use sparingly or remove):**');
    lines.push('');
    for (const intensifier of voice.hollowIntensifiers.slice(0, 5)) {
      lines.push(`- "${intensifier.phrase}" (${intensifier.count} uses) - ${intensifier.alternative}`);
    }
    lines.push('');
  } else {
    lines.push('**This writer avoids hollow intensifiers** - their sincerity comes through in specifics and admissions, not performative markers.');
    lines.push('');
  }

  // ============================================================
  // PUNCTUATION & MECHANICAL TELLS (NEW SECTION)
  // ============================================================
  if (punctuation || functionWords) {
    lines.push('---');
    lines.push('');
    lines.push('## PUNCTUATION & MECHANICAL TELLS');
    lines.push('');
    lines.push('*These micro-level patterns are invisible to readers but scream "AI" to detection systems. Match them exactly.*');
    lines.push('');
    
    // DASH USAGE - Critical AI tell
    if (punctuation) {
      lines.push('### Dash Usage (Critical AI Tell)');
      lines.push('');
      
      const { dashTypes, dashConsistency } = punctuation;
      const totalDashes = dashTypes.hyphen + dashTypes.enDash + dashTypes.emDash;
      
      if (totalDashes > 0) {
        // Determine what this writer uses
        if (dashTypes.emDash === 0 && dashTypes.enDash === 0) {
          lines.push('**This writer uses hyphens (-) exclusively for clause breaks. Never em-dashes or en-dashes.**');
          lines.push('');
          lines.push('```');
          lines.push('CORRECT:   "The syntax looks simple - a few Disallow statements"');
          lines.push('WRONG:     "The syntax looks simple — a few Disallow statements"');
          lines.push('WRONG:     "The syntax looks simple – a few Disallow statements"');
          lines.push('```');
        } else if (dashTypes.emDash === 0) {
          lines.push(`**This writer uses hyphens (-) and en-dashes (\\u2013) but NEVER em-dashes (\\u2014).**`);
          lines.push('');
          lines.push('Em-dashes are a major AI tell. If you see one in your output, replace it immediately.');
        } else {
          lines.push(`**Dash distribution in corpus:**`);
          lines.push(`- Hyphens (-): ${dashTypes.hyphen}`);
          lines.push(`- En-dashes (\\u2013): ${dashTypes.enDash}`);
          lines.push(`- Em-dashes (\\u2014): ${dashTypes.emDash}`);
          lines.push('');
          lines.push(`Dominant type: **${dashConsistency.dominantType}** (${dashConsistency.consistencyScore}% consistency)`);
        }
        lines.push('');
        
        if (dashConsistency.aiDetectionFlag) {
          lines.push(`**Warning:** ${dashConsistency.note}`);
          lines.push('');
        }
      } else {
        lines.push('*Minimal dash usage detected in corpus.*');
        lines.push('');
      }
      
      // Other punctuation patterns
      lines.push('### Other Punctuation Patterns');
      lines.push('');
      lines.push('| Pattern | Corpus Value | Guidance |');
      lines.push('|---------|--------------|----------|');
      lines.push(`| Quotation style | ${punctuation.quotationStyle} | Use ${punctuation.quotationStyle} quotes consistently |`);
      lines.push(`| Comma density | ${punctuation.commaDensity.toFixed(2)}/sentence | ${punctuation.commaDensity < 0.5 ? 'Sparse commas - direct style' : punctuation.commaDensity > 1.0 ? 'Heavy comma use - complex clauses' : 'Moderate comma use'} |`);
      lines.push(`| Semicolons | ${punctuation.semicolonFrequency.toFixed(1)}/1000 words | ${punctuation.semicolonFrequency < 1 ? 'Rarely used' : 'Occasional use for complex lists'} |`);
      lines.push(`| Exclamations | ${punctuation.exclamationFrequency.toFixed(1)}/1000 words | ${punctuation.exclamationFrequency < 2 ? 'Restrained enthusiasm' : 'Expressive style'} |`);
      lines.push(`| Parentheticals | ${punctuation.parentheticalFrequency.toFixed(1)}/1000 words | ${punctuation.parentheticalFrequency > 10 ? 'Frequent asides (conversational)' : 'Limited parentheticals'} |`);
      lines.push('');
    }
    
    // FUNCTION WORD SIGNATURE
    if (functionWords && (functionWords.distinctive.length > 0 || functionWords.avoided.length > 0)) {
      lines.push('### Function Word Signature');
      lines.push('');
      lines.push('These small words create an invisible fingerprint. AI models have predictable function word distributions. This writer deviates in specific ways:');
      lines.push('');
      
      if (functionWords.distinctive.length > 0) {
        lines.push('**Words this writer uses MORE than typical English:**');
        lines.push('');
        for (const word of functionWords.distinctive.slice(0, 5)) {
          const zScoreData = functionWords.zScores[word.word];
          const interpretation = zScoreData ? ` (z=${zScoreData.zScore.toFixed(2)})` : '';
          lines.push(`- **"${word.word}"**${interpretation} - Use freely, it's characteristic`);
        }
        lines.push('');
      }
      
      if (functionWords.avoided.length > 0) {
        lines.push('**Words this writer AVOIDS (use sparingly):**');
        lines.push('');
        for (const word of functionWords.avoided.slice(0, 5)) {
          const zScoreData = functionWords.zScores[word.word];
          const interpretation = zScoreData ? ` (z=${zScoreData.zScore.toFixed(2)})` : '';
          let alternative = '';
          
          // Provide alternatives for commonly avoided words
          if (word.word === 'was') alternative = ' - Use present tense or active constructions';
          if (word.word === 'it') alternative = ' - Name the thing directly';
          if (word.word === 'would') alternative = ' - Use direct statements';
          if (word.word === 'the') alternative = ' - Use "this", "that", or possessives';
          
          lines.push(`- **"${word.word}"**${interpretation}${alternative}`);
        }
        lines.push('');
      }
      
      if (functionWords.britishMarkers.length > 0) {
        lines.push('**British English markers detected:**');
        lines.push('');
        for (const marker of functionWords.britishMarkers) {
          lines.push(`- "${marker.word}" (${marker.count} uses)`);
        }
        lines.push('');
      }
    }
    
  }
  
  // ============================================================
  // VALIDATION METRICS
  // ============================================================
  lines.push('---');
  lines.push('');
  lines.push('## VALIDATION METRICS (Check After Writing)');
  lines.push('');
  lines.push("*These numbers validate the voice. They don't create it.*");
  lines.push('');
  lines.push('After writing from immersion, check if your output naturally produces:');
  lines.push('');
  
  lines.push('### Core Metrics');
  lines.push('');
  lines.push('| Metric | Target | Purpose |');
  lines.push('|--------|--------|---------|');
  lines.push(`| Sentence length variation | ${sentence.length.stdDev.toFixed(1)}+ stddev | Naturalness marker |`);
  lines.push(`| First-person frequency | ${voice.firstPerson.frequency.toFixed(2)}/100 words | Authority level |`);
  lines.push(`| Hedging frequency | ${voice.hedgingLanguage.frequency.toFixed(2)}/100 words | Confidence level |`);
  if (paragraph) {
    lines.push(`| Sentences per paragraph | ${paragraph.sentencesPerParagraph.mean.toFixed(1)} +/-${paragraph.sentencesPerParagraph.stdDev.toFixed(1)} | Rhythm variation |`);
  }
  if (punctuation && punctuation.dashTypes.emDash === 0) {
    lines.push(`| Em-dashes | 0 | Never use em-dashes |`);
  }
  lines.push('');
  
  lines.push('### Why These Numbers Matter');
  lines.push('');
  lines.push("If your writing matches the immersion examples above, these numbers will naturally align. If they don't, you're probably:");
  lines.push('');
  lines.push('- Over-thinking and becoming mechanical (high uniformity)');
  lines.push('- Using generic instead of specific language (low authenticity markers)');
  lines.push('- Following rules instead of channeling voice (feels stiff)');
  lines.push('');
  lines.push("**Fix:** Go back to the examples. Read them aloud again. Write from that energy, not from checklist compliance.");
  lines.push('');
  
  // Final reminder
  lines.push('---');
  lines.push('');
  lines.push('## FINAL REMINDER');
  lines.push('');
  lines.push("This guide gives you the patterns. But patterns aren't voice.");
  lines.push('');
  lines.push('Voice comes from reading the examples, feeling the rhythm, understanding the energy, and then writing from that internalized sense.');
  lines.push('');
  lines.push("The statistics at the end? They're just proof you got it right.");
  lines.push('');
  lines.push("Now go write. Channel that voice. Don't count words or check z-scores until after.");
  lines.push('');
  
  return lines.join('\n');
}

export { generateNarrativeGuideInternal as generateNarrativeGuide };
